"""Input plausibility warnings and feature-drift detection, both against the training
baseline in api/feature_baseline.json (generated by build_feature_baseline.py).

WARNINGS NEVER REJECT INPUT. A value outside the baseline range is scored exactly as it would
have been without this module; the response simply carries an `input_warnings` list saying
so. That is the correct behaviour for a detector: out-of-range input may be precisely the
anomaly the system exists to catch, and a guard that rejected it would suppress detections.
The warning is for the operator, not the pipeline.

Why this exists
---------------
While building Phase 1 it turned out that a hand-written, physically sensible-looking feature
vector -- pDOP 1.4, hAcc 2.5 m, numSV 18 -- scored as "attack" with p = 0.60 on the shipped
model, with no error, no warning, and nothing in the response to suggest the input was
malformed. The features are on the raw Jammertest CSV scales (pDOP sits around 0.01, not 1.4)
and a caller working from physical intuition rather than INGESTION_CONTRACT.md gets a
confident wrong answer. This module makes that visible.

What it catches, and what it does not -- MEASURED, not claimed
--------------------------------------------------------------
Against that exact wrong-scale vector, this guard flags **pDOP only**. The other three
mis-scaled fields land inside the baseline range and pass silently:

  - `hAcc` 2.5: the baseline's own p99.9 is 4,294,967.295, because the real training data
    contains the u-blox "invalid" sentinel (2^32-1 mm). The upper bound is therefore
    meaningless and no value can exceed it. Same for `vAcc`.
  - `numSV` 18: the baseline spans 0-32. 18 is ordinary.
  - `n_sats_l1` 18: the baseline spans 1-49. 18 is ordinary.

So: a per-feature range check catches gross scale errors on features whose training range is
tight, and misses errors that happen to land inside a wide one. It is a smoke detector, not a
validator. One warning out of four mis-scaled fields is still the difference between a silent
wrong answer and a visible one -- but nobody should read `input_warnings: []` as "this input
is correct".

Cross-feature consistency checks (does `n_sats_l1` exceed `numSV` the way it should? is
`snr_l1_min` <= `snr_l1_mean`?) would catch more, and are not implemented. That is a real gap,
recorded in ASSUMPTIONS_PRODUCTION.md rather than glossed.
"""
from __future__ import annotations

import json
import math
from pathlib import Path

BASELINE_PATH = Path(__file__).resolve().parent / "feature_baseline.json"

# PSI convention, widely used in credit-risk monitoring and adopted here for the same reason
# it is used there: it is a simple, interpretable, thresholded divergence over binned
# distributions. These cut points are the conventional ones, not values derived from this
# project's data -- stated so nobody reads them as a measurement.
PSI_MINOR = 0.10    # >= this: noticeable shift, worth looking at
PSI_MAJOR = 0.25    # >= this: substantial shift, conventionally "investigate/retrain"
PSI_EPSILON = 1e-6  # floor for empty bins, so a zero proportion cannot produce log(0)

DRIFT_MIN_SAMPLES = 100  # below this, PSI over 10 bins is too noisy to report


class BaselineUnavailable(RuntimeError):
    pass


class FeatureBaseline:
    """Loads api/feature_baseline.json once and answers plausibility / drift questions."""

    def __init__(self, path: Path | None = None):
        self.path = Path(path) if path else BASELINE_PATH
        if not self.path.exists():
            raise BaselineUnavailable(
                f"No feature baseline at {self.path}. Run `python build_feature_baseline.py`."
            )
        payload = json.loads(self.path.read_text(encoding="utf-8"))
        self.generated_at: str = payload.get("generated_at", "unknown")
        self.n_rows: int = payload.get("n_rows", 0)
        self.n_runs = payload.get("n_runs")
        self.method: dict = payload.get("method", {})
        self.provenance: str = payload.get("provenance", "")
        self.features: dict[str, dict] = payload["features"]

    # ------------------------------------------------------------------ warnings

    def check(self, features: dict) -> list[dict]:
        """Return a list of warnings for one feature vector. Empty list means every supplied
        value fell inside its widened baseline range -- which is not the same as 'correct'."""
        warnings: list[dict] = []
        for name, value in features.items():
            if value is None:
                continue
            stats = self.features.get(name)
            if stats is None:
                continue  # not a model feature; the model ignores it anyway
            try:
                v = float(value)
            except (TypeError, ValueError):
                continue
            if math.isnan(v) or math.isinf(v):
                warnings.append({
                    "feature": name, "value": None, "direction": "not_finite",
                    "bound_low": stats["bound_low"], "bound_high": stats["bound_high"],
                    "baseline_median": stats["median"],
                    "message": f"{name} is not a finite number; it will be imputed with the "
                               f"training median ({stats['median']:.4g}).",
                })
                continue
            if v < stats["bound_low"]:
                direction = "below_baseline_range"
            elif v > stats["bound_high"]:
                direction = "above_baseline_range"
            else:
                continue
            warnings.append({
                "feature": name,
                "value": v,
                "direction": direction,
                "bound_low": stats["bound_low"],
                "bound_high": stats["bound_high"],
                "baseline_median": stats["median"],
                "message": (
                    f"{name}={v:.6g} is {'below' if direction.startswith('below') else 'above'} "
                    f"the training baseline range [{stats['bound_low']:.6g}, "
                    f"{stats['bound_high']:.6g}] (baseline median {stats['median']:.6g}). "
                    f"Scored anyway -- this is a warning, not a rejection. If this was not "
                    f"expected, check units and scale against INGESTION_CONTRACT.md."
                ),
            })
        return sorted(warnings, key=lambda w: w["feature"])

    # ------------------------------------------------------------------ drift

    def psi(self, name: str, values: list[float]) -> dict | None:
        """Population Stability Index for one feature against its baseline bins.

            PSI = sum over bins of (live_prop - base_prop) * ln(live_prop / base_prop)

        Returns None when the feature has no usable binning (a near-constant baseline column
        such as fixType) -- reported as such rather than silently omitted."""
        stats = self.features.get(name)
        if stats is None or stats.get("psi_degenerate"):
            return None
        edges = stats["psi_bin_edges"]
        base = stats["psi_baseline_proportions"]
        if not edges or not base:
            return None

        # JSON cannot hold infinity; build_feature_baseline.py writes the open outer edges as
        # null and they are restored here.
        numeric_edges = [(-math.inf if e is None and i == 0 else
                          math.inf if e is None else e) for i, e in enumerate(edges)]
        if numeric_edges[-1] is None:
            numeric_edges[-1] = math.inf

        clean = [float(v) for v in values
                 if v is not None and not math.isnan(float(v)) and not math.isinf(float(v))]
        if len(clean) < DRIFT_MIN_SAMPLES:
            return None

        counts = [0] * (len(numeric_edges) - 1)
        for v in clean:
            for i in range(len(counts)):
                lo, hi = numeric_edges[i], numeric_edges[i + 1]
                # Half-open bins, with the final bin closed so the maximum value lands in it.
                if (lo <= v < hi) or (i == len(counts) - 1 and v == hi):
                    counts[i] += 1
                    break
        total = sum(counts) or 1
        live = [c / total for c in counts]

        psi_value = 0.0
        for live_p, base_p in zip(live, base):
            lp = max(live_p, PSI_EPSILON)
            bp = max(base_p, PSI_EPSILON)
            psi_value += (lp - bp) * math.log(lp / bp)

        return {
            "feature": name,
            "psi": psi_value,
            "n_live": len(clean),
            "severity": ("major" if psi_value >= PSI_MAJOR
                         else "minor" if psi_value >= PSI_MINOR
                         else "none"),
            "live_proportions": [round(p, 6) for p in live],
            "baseline_proportions": [round(p, 6) for p in base],
        }
